name: continuous_integration

# Controls when the action will run.
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: androidsdk/android-30:latest
    steps:
      - name: co
        uses: actions/checkout@v2
      - name: build
        run: ./TodoTasker/gradlew --no-daemon build
      - name: test
        run: ./TodoTasker/gradlew --no-daemon test
